services:
  authapi:
    image: davideshett/auth:19.04.24.01
    container_name: 'authapi'
    restart: always
    ports:
      - 4000:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  auth-fe:
    image: authtest:25.04.24.01
    container_name: 'auth-fe'
    ports:
      - 3000:3000